# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a81ca514030ab00a75a90eeda83e004e6572c058dfb059e94d3941a7355350a0274f16a36c8e3557da4353212ea5d8cd537a9aeca840f89604e2742829390a

test:
  secret_key_base: 58f45cf7e5c8a06451e5dfb9660dc648aceb9c1eca89ffda7d051730d3cb9290754387df9eeb8d89574666ee08ffcaa41b2ed207406a8b1fed9b926735346cbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
